### ISSUE TITLE
g++ 6.1 misleading indentation warning

### ISSUE THREAD

**Issue by christophermorley** [boostorg/ublas#40]
This looks like a real error. The brace at the end of line 2227 of matrix_expression.hpp looks like it should properly be at line 2224.

/dev/boost/1_57_0/include/boost/numeric/ublas/matrix_expression.hpp: In member function ‘void boost::numeric::ublas::matrix_binary<E1, E2, F>::const_iterator1::increment(boost::numeric::ublas::sparse_bidirectional_iterator_tag)’:
/home/cmm/dev/boost/1_57_0/include/boost/numeric/ublas/matrix_expression.hpp:2224:17: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
                 if (it2_ != it2_end_)
                 ^~

**Comment by eddelbuettel** [comment]
Seconded. I am still seeing this in 1.65.0.

**Comment by MartinDuyTat** [comment]
Hello, I recently installed version 1.68.0 and this is still there. Can anyone please confirm if it's a bug or not? Thanks!

**Comment by iljah** [comment]
Asked about this at higher level: https://github.com/boostorg/boost/issues/233

**Comment by bassoy** [comment]
Thanks for your comments. This is solved now! We are hopefully also going to introduce clang-tidy and clang-format.
