### ISSUE TITLE
Matrix/Tensor Factorization

### ISSUE THREAD

**Issue by thomasyang1207** [boostorg/ublas#66]
Operations such as matrix multiplication are BLAS level 3 operations, while matrix addition is level 1. Suppose we have the following computation of 4 matrices: 

A * C + B * D; 

Suppose A = B, but the user of the library may or may not know this. Would it be a good idea to find a way to compute this instead: 

A (C+ D)

I think this is a rather trivial topic, but I thought it might be cool for uBLAS to have this

**Comment by yimyom** [comment]
there was a project on optimizing the template tree with interesting
results. It was done by an excellent student in 2014.

It would be nice to revive this project and try to extend it. Are you
interested?
The project is here: https://github.com/BoostGSoC14/boost.ublas

**Comment by bassoy** [comment]
Hi all,

we are now trying to do this with Boost/Yap which is very convenient to use
and has already a builtin transform function.

Best
Cem






David Bellot <notifications@github.com> schrieb am Mo., 1. Apr. 2019, 11:21:

> there was a project on optimizing the template tree with interesting
> results. It was done by an excellent student in 2014.
>
> It would be nice to revive this project and try to extend it. Are you
> interested?
> The project is here: https://github.com/BoostGSoC14/boost.ublas
>
