### ISSUE TITLE
C++17 deprecates std::iterator

### ISSUE THREAD

**Issue by zvilius** [boostorg/ublas#76]
Compiling with Visual Studio 2017 with c++17 language flag set:

`warning C4996: 'std::iterator<IC,T,ptrdiff_t,_Ty *,_Ty &>::iterator_category': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17.
`
Results from using one of the iterator base classes, e.g. `random_access_iterator_base`.

Not urgent as it is easy enough to suppress the warning, but I thought I'd note the issue since I don't see it here already.

**Comment by bassoy** [comment]
thanks @zvilius . We will hopefully soon migrate to C++17 and use a different approach for iterating over matrix and tensor index spaces.

**Comment by jwakely** [comment]
Looks like this is (partially?) fixed by #100

**Comment by bassoy** [comment]
> Looks like this is (partially?) fixed by #100

Yes. True. 
Yet, PR https://github.com/boostorg/ublas/pull/100 has not been merged.
However, PR https://github.com/boostorg/ublas/pull/97 with the same changes has been merged into develop branch.
