### ISSUE TITLE
boost 1.73.0 - boost::numeric::ublas::matrix compilation issues with gcc-10 with c++20 support

### ISSUE THREAD

**Issue by eladedgy** [boostorg/ublas#96]
Problem description:
When compiling the following example:
#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/io.hpp>

int main () {
    using namespace boost::numeric::ublas;
    matrix<double> m (3, 3);
    for (unsigned i = 0; i < m.size1 (); ++ i)
        for (unsigned j = 0; j < m.size2 (); ++ j)
            m (i, j) = 3 * i + j;
    std::cout << m << std::endl;
}

with gcc-10 with -std=gnu++2a flag, compilation breaks
Running the same compilation line with -std=gnu++17 passes

boost build command lines:
./bootstrap.sh --prefix="${PWD}/../boost-bin"
./b2
./b2 install

Compiled on ubuntu 18.04, added gcc-10:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt install gcc-10 g++-10

Compilation error:
test_boost.cpp:9:27:   required from here
boost-bin/include/boost/numeric/ublas/storage.hpp:79:30: error: ‘class std::allocator<double>’ has no member named ‘construct’
   79 |                       alloc_.construct(d, value_type());

**Comment by bassoy** [comment]
Thanks @eladedgy for using boost.ublas.
We are aware of this issue and we already included a bugfix for the upcoming release boost release. 
Please have a look at the already merged PR https://github.com/boostorg/ublas/pull/83.
I will close this issue as the bug is fixed with commit  https://github.com/boostorg/ublas/commit/47a314dd01d1adacaaf7265c7c644f8f70afd402 on the development branch.

**Comment by mclow** [comment]
I see this commit in `develop`, but not in `master`.

**Comment by eladedgy** [comment]
Please notice I've tested it on 1.74 beta 1 as well as issue is reproducible on that branch

**Comment by bassoy** [comment]
> I see this commit in `develop`, but not in `master`.

Yes. I am not sure if we can pull the commit into master as we are late for the 1.74 release which will be closed for merges in one day. We need two contributors to 

@mclow what is your advise?

**Comment by eladedgy** [comment]
Hi,
gcc-10 is already released for a couple of months, and it's supported out-of-the-box in Ubuntu 20.04 LTS
releasing 1.74.0 with this bug means no one will be able to compile with C++20 on those machines or Ubuntu 20.04 based containers
This is not a minor issue which can be released

**Comment by jwakely** [comment]
Fedora 32 (released three months ago) also uses GCC 10.

**Comment by glenfe** [comment]
Fixed in develop with #103.

**Comment by eladedgy** [comment]
Problem exists in 1.75.0 as well
